INSERT INTO event (event_name,location_of_event,start_time,end_time,dated,Imageurl) VALUES ('farewell','Town Hall','10:00:00','12:00:00','2023-02-10','https://via.placeholder.com/600/92c952');
INSERT INTO event (event_name,location_of_event,start_time,end_time,dated,Imageurl) VALUES ('annual function','Town Hall','12:00:00','14:00:00','2023-02-11','https://via.placeholder.com/600/92c952');
INSERT INTO event (event_name,location_of_event,start_time,end_time,dated,Imageurl) VALUES ('farewell','Zorawar Auditorium','10:00:00','12:00:00','2023-02-12','https://via.placeholder.com/600/47p952');
INSERT INTO event (event_name,location_of_event,start_time,end_time,dated,Imageurl) VALUES ('induction','Town Hall','12:00:00','14:00:00','2023-02-10','https://via.placeholder.com/600/45v952');
INSERT INTO event (event_name,location_of_event,start_time,end_time,dated,Imageurl) VALUES ('workshop','Zorawar Auditorium','13:00:00','15:00:00','2023-02-10','https://via.placeholder.com/600/87c952');
INSERT INTO student (first_name,last_name,age,department) VALUES ('Abhishek','Manhas',26,'Computer Science');
INSERT INTO student (first_name,last_name,age,department) VALUES ('Vijay','Thakur',25,'Botany');
INSERT INTO student (first_name,last_name,age,department) VALUES ('Mohit','Sharma',25,'Zoology');
INSERT INTO student (first_name,last_name,age,department) VALUES ('Vivek','Sharma',26,'Physics');
INSERT INTO student (first_name,last_name,age,department) VALUES ('Sahil','Verma',26,'Computer Science');
